/* eslint-disable n/file-extension-in-import */
import {Box, Typography} from '@mui/material';
import type {Metadata} from 'next';
import Header from './components/header/header';
import {Providers} from './providers/providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<Box
						sx={{
							display: 'flex',
							flexDirection: 'column',
							height: '100vh',
							width: '100vw',
						}}
					>
						<Header />
						{children}
					</Box>
				</Providers>
			</body>
		</html>
	);
}
